version: '3.9'

services:
  backend:
    build: ./app
    environment:
      - MONGO_URI=mongodb://admin:admin@mongo:27017
    ports:
      - 8000:8000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
